*********Table User Store***************************
CREATE TABLE USERSTORE (
		NAME VARCHAR2(100),
		USERNAME VARCHAR2(20) NOT NULL,
		PASSWORD VARCHAR2(20),
		USER_TYPE VARCHAR2(100),
		LAST_LOGGED TIMESTAMP(11),
		LOGGED_STATUS NUMBER(2 , 0)
	);

CREATE UNIQUE INDEX SYS_C007170 ON USERSTORE (USERNAME ASC);

ALTER TABLE USERSTORE ADD CONSTRAINT SYS_C007170 PRIMARY KEY (USERNAME);


	
*******************Table Patient*************************************
CREATE TABLE TBL_PATIENT (
		PATIENT_SSN NUMBER(9 , 0),
		PATIENT_ID NUMBER(9 , 0) NOT NULL,
		PATIENT_NAME VARCHAR2(100),
		ADDRESS VARCHAR2(100),
		AGE NUMBER(3 , 0),
		DATE_OF_JOINING DATE,
		ROOM_TYPE VARCHAR2(50),
		CITY VARCHAR2(50),
		STATE VARCHAR2(50),
		STATUS VARCHAR2(10)
	);

CREATE UNIQUE INDEX SYS_C007174 ON TBL_PATIENT (PATIENT_ID ASC);

ALTER TABLE TBL_PATIENT ADD CONSTRAINT SYS_C007174 PRIMARY KEY (PATIENT_ID);


***********************Table Medicine*************************************************

CREATE TABLE TBL_MEDICINE (
		MEDICINE_ID NUMBER(10 , 0) NOT NULL,
		MEDICINE_NAME VARCHAR2(100),
		RATE NUMBER
	);

CREATE UNIQUE INDEX SYS_C007190 ON TBL_MEDICINE (MEDICINE_ID ASC);

ALTER TABLE TBL_MEDICINE ADD CONSTRAINT SYS_C007190 PRIMARY KEY (MEDICINE_ID);


	************************Table issued Medicine*****************************************
	CREATE TABLE TBL_ISSUED_MEDICINE (
		PATIENT_ID NUMBER(10 , 0) NOT NULL,
		MEDICINE_NAME VARCHAR2(100),
		QUANTITY NUMBER,
		MEDICINE_ID NUMBER(10 , 0) NOT NULL,
		RATE NUMBER,
		TOTAL_AMOUNT NUMBER
	);

CREATE UNIQUE INDEX SYS_C007192 ON TBL_ISSUED_MEDICINE (PATIENT_ID ASC, MEDICINE_ID ASC);

ALTER TABLE TBL_ISSUED_MEDICINE ADD CONSTRAINT SYS_C007192 PRIMARY KEY (PATIENT_ID, MEDICINE_ID);

ALTER TABLE TBL_ISSUED_MEDICINE ADD CONSTRAINT SYS_C007193 FOREIGN KEY (MEDICINE_ID)
	REFERENCES TBL_MEDICINE (MEDICINE_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;
	********************************Diagnostic Table**********************************************************
	
	CREATE TABLE DIAGNOSTICS (
		PATIENT_ID NUMBER(10 , 0),
		DIAGNOSIS VARCHAR2(100),
		DIAGNOSIS_RATE NUMBER
	);

ALTER TABLE DIAGNOSTICS ADD CONSTRAINT SYS_C007194 FOREIGN KEY (PATIENT_ID)
	REFERENCES TBL_PATIENT (PATIENT_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

*******************************Sequence For Patientid Generation********************************************************
CREATE SEQUENCE PATIENT_ID
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    MAXVALUE 9999999999
    CYCLE
    CACHE 2;
    
