/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.104
 * Generated at: 2020-07-03 14:51:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;

public final class medicines_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<style>\r\n");
      out.write("    /* Add some padding on document's body to prevent the content\r\n");
      out.write("    to go underneath the header and footer */\r\n");
      out.write("    body{        \r\n");
      out.write("        padding-top: 60px;\r\n");
      out.write("        padding-bottom: 40px;\r\n");
      out.write("    }\r\n");
      out.write("    .container{\r\n");
      out.write("        margin: 0 auto; /* Center the DIV horizontally */\r\n");
      out.write("    }\r\n");
      out.write("    .fixed-header, .fixed-footer{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        position: fixed;        \r\n");
      out.write("        background: #333;\r\n");
      out.write("        padding: 10px 0;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    .fixed-header{\r\n");
      out.write("        top: 0;\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("    /* Some more styles to beutify this example */\r\n");
      out.write("  \r\n");
      out.write("    .container p{\r\n");
      out.write("        line-height: 200px; /* Create scrollbar to test positioning */\r\n");
      out.write("    }\r\n");
      out.write("    p.detail\r\n");
      out.write("    {\r\n");
      out.write("    color:yellow;\r\n");
      out.write("    line-height: 0px;\r\n");
      out.write("    font-size: x-large;\r\n");
      out.write("    }\r\n");
      out.write("    span.name{\r\n");
      out.write("    \tcolor:white;\r\n");
      out.write("    \tfont-size: x-large;\r\n");
      out.write("    }\r\n");
      out.write("    tr\r\n");
      out.write("    {\r\n");
      out.write("    height: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    span.aestric\r\n");
      out.write("    {\r\n");
      out.write("    color: red;\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function disableBackButton()\r\n");
      out.write(" {\r\n");
      out.write("  //location.href(\"logout.html\");\r\n");
      out.write("\r\n");
      out.write(" }\r\n");
      out.write("if(window.history.forward(1) != null)\r\n");
      out.write("         window.history.forward(1);\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("form.example input[type=text] {\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  border: 1px solid grey;\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 80%;\r\n");
      out.write("  background: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.example button {\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 20%;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  background: #2196F3;\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  border: 1px solid grey;\r\n");
      out.write("  border-left: none;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.example button:hover {\r\n");
      out.write("  background: #0b7dda;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form.example::after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  clear: both;\r\n");
      out.write("  display: table;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"fixed-header\">\r\n");
      out.write("<div class=\"container\" style=\"padding-left: 493px;\">\r\n");
      out.write("  <p class=\"detail\" >TATA<span class=\"name\">&nbsp;Hospital Management System</span></p>\r\n");
      out.write("</div>\r\n");
      out.write(" </div>\r\n");
      out.write("   <div class=\"container\" style=\"width:1358px;height:500px\">\r\n");
      out.write("    <p>\r\n");
      out.write(" <div id= \"serchdiv2\"  style=\"padding-top: 39px;\"> \r\n");
      out.write("<form action=\"MedicineServlet\" method=\"POST\" name=\"billForm\">\r\n");
      out.write("   ");

      
        Object patientid="";
        Object name ="";
        Object age="";
        Object doj= "";
        Object bedtype="";
        Object address="";
        Object dischargedate="";
        Object noOfDaysBetween="";
        Object roomcharge="";
        Object medicinename="";
        Object quantity="";
        Object rate="";
        Object amount=""; 
        if(request.getAttribute("patientid")!=null)
        {
   			  patientid=request.getAttribute("patientid");
        }
        if(request.getAttribute("name")!=null)
        {
     		name =request.getAttribute("name");
        }
        if(request.getAttribute("age")!=null)
        {
              age=request.getAttribute("age");
        }
        if(request.getAttribute("doj")!=null ||request.getAttribute("bedtype")!=null||request.getAttribute("address")!=null||request.getAttribute("dischargedate")!=null ||request.getAttribute("noOfDaysBetween")!=null||request.getAttribute("roomcharge")!=null||request.getAttribute("medicinename")!=null||request.getAttribute("quantity")!=null||request.getAttribute("rate")!=null||request.getAttribute("amount")!=null)
        {
          
        doj= request.getAttribute("doj");
        bedtype=request.getAttribute("bedtype");
        address=request.getAttribute("address");
        dischargedate=request.getAttribute("dischargedate");
        noOfDaysBetween=request.getAttribute("noOfDaysBetween");
        roomcharge=request.getAttribute("roomcharge");
       // medicinename=request.getAttribute("medicinename");
        //quantity=request.getAttribute("quantity");
       // rate=request.getAttribute("rate");
       // amount=request.getAttribute("amount");
      //  System.out.println("medname>>>>>>>>>>>>>>>>>>>>>"+medicinename);
        }
        
      out.write("\r\n");
      out.write("        <h2 style=\"padding-left: 474px;\">Pharmacy</h2>\r\n");
      out.write("<table style=\"width:80%\" align=\"center\" border=\"2\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- <tr >\r\n");
      out.write("<td >Patient Id\r\n");
      out.write("<font color=\"red\">*</font>\r\n");
      out.write("</td>\r\n");
      out.write("<td><input type=\"text\" name=\"pid\" size=35 required=\"required\"></td>\r\n");
      out.write("<td><input type=\"submit\" name=\"submit\" value=\"SUBMIT\" required=\"required\"\"></td>\r\n");
      out.write("</tr> -->\r\n");
      out.write("<tr align=\"center\">\r\n");
      out.write("</tr>\r\n");
      out.write("<tr bgcolor=\"black\">\r\n");
      out.write("<th>\r\n");
      out.write("<font color=\"white\">PatientID</font>\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("<font color=\"white\">Name</font>\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("<font color=\"white\">Age</font>\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("<font color=\"white\">Address</font>\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("<font color=\"white\">DOJ</font>\r\n");
      out.write("</th>\r\n");
      out.write("\r\n");
      out.write("<th>\r\n");
      out.write("<font color=\"white\">Type of Room</font>\r\n");
      out.write("</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td style=\"width: 10px;\"><input type=\"text\" id=\"patientid\" name=\"pid\" placeholder=\"Search..\" name=\"search2\" required=\"required\" style=\"padding: 8px;\r\n");
      out.write("  \r\n");
      out.write("  border: 1px solid grey;\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 76%;\r\n");
      out.write("  background: #f1f1f1;\" value=");
      out.print(patientid );
      out.write(" >\r\n");
      out.write("  <button type=\"submit\" style=\" float: left;\r\n");
      out.write("  width: 24%;\r\n");
      out.write("  padding: 6px;\r\n");
      out.write("  background: searchicon.jpg;\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  border: 1px solid grey;\r\n");
      out.write("  border-left: none;\r\n");
      out.write("  cursor: pointer;\"><i class=\"fa fa-search\" aria-hidden=\"true\" ></i></button></td>\r\n");
      out.write("  \r\n");
      out.write("  <td>");
      out.print(name );
      out.write("</td> <td>");
      out.print(age );
      out.write("</td> <td>");
      out.print(address );
      out.write("</td> <td>");
      out.print(doj );
      out.write("</td> <td>");
      out.print(bedtype );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<!-- <tr >\r\n");
      out.write("<td></td>\r\n");
      out.write("<td></td>\r\n");
      out.write("<td></td>\r\n");
      out.write("<td>No. of Days : </td>\r\n");
      out.write("<td>Bill for Room :</td>\r\n");
      out.write("</tr> -->\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<p>\r\n");
      out.write("   <h2 style=\"padding-left: 474px;\">Medicines Issued</h2>\r\n");
      out.write("<table style=\"width:80%\" align=\"center\" border=\"2\" >\r\n");
      out.write("<tr bgcolor=\"black\">\r\n");
      out.write("<th>\r\n");
      out.write("<font color=\"white\">Medicine</font>\r\n");
      out.write("</th>\r\n");
      out.write("\r\n");
      out.write("<th>\r\n");
      out.write("<font color=\"white\">Quantity</font>\r\n");
      out.write("</th>\r\n");
      out.write("\r\n");
      out.write("<th>\r\n");
      out.write("<font color=\"white\">Rate</font>\r\n");
      out.write("</th>\r\n");
      out.write("\r\n");
      out.write("<th>\r\n");
      out.write("<font color=\"white\">Amount</font>\r\n");
      out.write("</th>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

try
{
Class.forName("oracle.jdbc.driver.OracleDriver");
String url="jdbc:oracle:thin:@localhost:1521:xe"; 
String username="system";
String password="system";
String query="select * from tbl_medicine  a inner join  (select * from tbl_issued_medicine) b on a.medicine_id=b.medicine_id inner join  (select patient_id from tbl_patient )c on b.patient_id=c.patient_id";
Connection conn=DriverManager.getConnection(url, username, password);
Statement stmt=conn.createStatement();
ResultSet rs=stmt.executeQuery(query);
while(rs.next())
{
	medicinename=rs.getString("medicine_name");
	quantity=rs.getInt("quantity");
	rate=rs.getInt("rate");
	amount=rs.getInt("quantity")*rs.getInt("rate");

      out.write("\r\n");
      out.write(" <tr><td>");
      out.print(medicinename );
      out.write("</td> <td>");
      out.print(quantity );
      out.write("</td><td>");
      out.print(rate );
      out.write("</td><td>");
      out.print(amount);
      out.write("</td></tr> \r\n");
      out.write("\r\n");
}
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<div style=\"padding-left: 592px;\"><input type=\"submit\" value=\"Issue Medicines\" name=\"Issue Medicines\"></div>\r\n");
      out.write("\r\n");

rs.close();
stmt.close();
conn.close();
}
catch(Exception e)
{
e.printStackTrace();
}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table style=\"width:80%\" align=\"center\" border=\"2\" >\r\n");
      out.write("<tr bgcolor=\"black\" >\r\n");
      out.write("<font color=\"white\">Medicine</font>\r\n");
      out.write("</th>\r\n");
      out.write("\r\n");
      out.write("<th>\r\n");
      out.write("<font color=\"white\">Quantity</font>\r\n");
      out.write("</th>\r\n");
      out.write("\r\n");
      out.write("<th>\r\n");
      out.write("<font color=\"white\">Rate</font>\r\n");
      out.write("</th>\r\n");
      out.write("\r\n");
      out.write("<th>\r\n");
      out.write("<font color=\"white\">Amount</font>\r\n");
      out.write("</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<div style=\"padding-left: 592px;\">\r\n");
      out.write("<input type=\"submit\" value=\"Add\" name=\"add\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"padding-left: 592px;\">\r\n");
      out.write("<br>\r\n");
      out.write("<input type=\"submit\" value=\"Update\" name=\"update\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</p>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
