--<ScriptOptions statementTerminator=";"/>

CREATE TABLE USERSTORE (
		USERNAME VARCHAR2(20),
		PASSWORD VARCHAR2(20),
		USER_TYPE VARCHAR2(100),
		LAST_LOGGED TIMESTAMP(11),
		LOGGED_STATUS NUMBER(2 , 0)
	);

