--<ScriptOptions statementTerminator=";"/>

CREATE TABLE USERSTORE (
		NAME VARCHAR2(100),
		USERNAME VARCHAR2(20) NOT NULL,
		PASSWORD VARCHAR2(20),
		USER_TYPE VARCHAR2(100),
		LAST_LOGGED TIMESTAMP(11),
		LOGGED_STATUS NUMBER(2 , 0)
	);

CREATE UNIQUE INDEX SYS_C007170 ON USERSTORE (USERNAME ASC);

ALTER TABLE USERSTORE ADD CONSTRAINT SYS_C007170 PRIMARY KEY (USERNAME);

